module Evergreen.Migrate.V5 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import AssocSet
import Evergreen.V4.Types
import Evergreen.V5.Types
import Lamdera.Migrations exposing (..)
import Types exposing (Key(..), PlayerMovementDirection(..))


frontendModel : Evergreen.V4.Types.FrontendModel -> ModelMigration Evergreen.V5.Types.FrontendModel Evergreen.V5.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V4.Types.BackendModel -> ModelMigration Evergreen.V5.Types.BackendModel Evergreen.V5.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V4.Types.FrontendMsg -> MsgMigration Evergreen.V5.Types.FrontendMsg Evergreen.V5.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V4.Types.ToBackend -> MsgMigration Evergreen.V5.Types.ToBackend Evergreen.V5.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V4.Types.BackendMsg -> MsgMigration Evergreen.V5.Types.BackendMsg Evergreen.V5.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V4.Types.ToFrontend -> MsgMigration Evergreen.V5.Types.ToFrontend Evergreen.V5.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_ToBackend : Evergreen.V4.Types.ToBackend -> Evergreen.V5.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V4.Types.NoOpToBackend ->
            Evergreen.V5.Types.NoOpToBackend

        Evergreen.V4.Types.PlayerInput dirs ->
            Evergreen.V5.Types.PlayerInput
                (AssocSet.map
                    (\dir ->
                        case dir of
                            Evergreen.V4.Types.K_Up ->
                                Evergreen.V5.Types.Up

                            Evergreen.V4.Types.K_W ->
                                Evergreen.V5.Types.Up

                            Evergreen.V4.Types.K_Down ->
                                Evergreen.V5.Types.Down

                            Evergreen.V4.Types.K_S ->
                                Evergreen.V5.Types.Up

                            Evergreen.V4.Types.K_Left ->
                                Evergreen.V5.Types.Left

                            Evergreen.V4.Types.K_A ->
                                Evergreen.V5.Types.Left

                            Evergreen.V4.Types.K_D ->
                                Evergreen.V5.Types.Right

                            Evergreen.V4.Types.K_Right ->
                                Evergreen.V5.Types.Right
                    )
                    dirs
                )
